In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from tabulate import tabulate
from sklearn.metrics import mean_squared_error, mean_absolute_error, root_mean_squared_error , r2_score

In [4]:
df = pd.read_csv(r'D:\NVIDIA AI Course\Udemy_NVIDIA-Certified_Associate_Generative_AI_LLMs_NCA-GENL_2025-1_Downloadly.ir\Advertising.csv')
df.head()

   Unnamed: 0     TV  radio  newspaper  sales
0           1  230.1   37.8       69.2   22.1
1           2   44.5   39.3       45.1   10.4
2           3   17.2   45.9       69.3    9.3
3           4  151.5   41.3       58.5   18.5
4           5  180.8   10.8       58.4   12.9

In [5]:
# drop unnamed column as it is useless
#inlace=True means we will drop this column permanently in the original df
df.drop(columns='Unnamed: 0',inplace=True)
df.head()

      TV  radio  newspaper  sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9

Mathematical representation of linear regression is (y = a + bx) where a is called y-interceptor and b is called slope and x is the feature.
in case we have multiple features, then the equation would be like this (Y= θ0+ θ1X1+θ2X2,….) where x1,x2 are called features,θ0 is the intercept and (θ1,θ2,θn) are coefficient

In [6]:
# let's assign the features and target
features_columns = ['TV','radio','newspaper']
X = df[features_columns]
y = df['sales']

In [7]:
#first let's split the data into 70% train and 30% test
X_train,X_test,y_train,y_test = train_test_split(X,y,random_state=4,test_size=0.3)
print(X_train.shape)
print(X_test.shape)

(140, 3)
(60, 3)

In [8]:
# feed the model to get a trained model
lr = LinearRegression()
lr.fit(X_train,y_train)

LinearRegression()

In [9]:
# get coefficients and interceptor
print(lr.coef_)
print(lr.intercept_)

[0.04533392 0.17715767 0.00553852]
3.09064436412511

In [10]:
#generate the predicted data
y_pred = lr.predict(X_test)
print(y_pred[:5])

[17.09777441 16.86148273 21.7761552  24.53812602 12.32008724]

Evaluation of the model to detect how the model perform
there are many evaluation functions like:
- mean absolute error
- mean squared error
- Root mean squared error
- R2 score

In [11]:
print(f"MAE is: {mean_absolute_error(y_test,y_pred)}")
print(f"MSE is: {mean_squared_error(y_test,y_pred)}")
# print(f"RMSE is: {mean_squared_error(y_test,y_pred, squared = False)}")
print(f"RMSE is: {root_mean_squared_error(y_test,y_pred)}")

MAE is: 1.2111525124980485
MSE is: 2.2237746679115578
RMSE is: 1.4912326002041256

In [12]:
# R2 score means how much variance can be explained by the given features
print(f"R2 Score is: {r2_score(y_test,y_pred)}")

R2 Score is: 0.9127220729596172