In [3]:
import pandas as pd

In [7]:
# series is one dimensional array
age = pd.Series([11,22,33,44])
print(age)

0    11
1    22
2    33
3    44
dtype: int64

In [8]:
# if we added multiple datatypes to the series it will be obeject
age = pd.Series([11,"Hello",True])
age

0       11
1    Hello
2     True
dtype: object

In [9]:
# we can change the index as well
age = pd.Series([11,22,33,44],index=['A','B','C','D'])
age

A    11
B    22
C    33
D    44
dtype: int64

In [12]:
#data frame like excell sheet (table of rows and columns)
studentInfo = pd.DataFrame({
    "Name": ["Mohamed","Nada","Celine","Malek"],
    "Age": [36,34,3,1],
    "isGraduated": [True,True,False,False]
})
studentInfo

      Name  Age  isGraduated
0  Mohamed   36         True
1     Nada   34         True
2   Celine    3        False
3    Malek    1        False

In [13]:
# we can do the same for the index
studentInfo = pd.DataFrame({
    "Name": ["Mohamed","Nada","Celine","Malek"],
    "Age": [36,34,3,1],
    "isGraduated": [True,True,False,False]
    }, index=['A','B','C','D'])
studentInfo

      Name  Age  isGraduated
A  Mohamed   36         True
B     Nada   34         True
C   Celine    3        False
D    Malek    1        False